### ISSUE TITLE
Pushing projects that aren't apps to Heroku

### ISSUE THREAD

**Issue by jackpandas** [Neats29/Learn-Heroku#2]
If a person tries to push to Heroku without a .json file (or ruby, php equivalents) heroku won't allow it. It might be worthwhile pointing out that heroku deployment should come after initial node development.

http://stackoverflow.com/questions/8361475/heroku-push-rejected-no-cedar-supported-app-detected

**Comment by Neats29** [comment]
Well without the scripts outlined in the package.json, the app will not be deployed anyway so you wouldn't be able to push without a package.json in the first place. But I can make it clearer at the start of the tutorial, thanks.
